config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "welcomes/index"
  resources :notes

  authenticated :user do
  	root "notes#index", as: "authenticated_root"
  end

  root "welcomes#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
	validates :title, length: {minimum: 3}
	validates :content, presence: true
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

	before_action :find_note, only: [:show, :edit, :update, :destroy]

	def index
		@notes = Note.where(user_id: current_user)
	end

	def new
		@note = current_user.notes.build
	end

	def create
		@note = current_user.notes.build(note_params)
		if @note.save
			redirect_to notes_path, notice: "記事本已建立"
		else
			render "new", alert: "記事本建立失敗，再檢查一下吧!"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @note.update(note_params)
			redirect_to notes_path, notice: "記事本修改成功"
		else
			render "edit", alert: "記事本修改失敗!"
		end
	end

	def destroy
		@note.destroy
		redirect_to notes_path, alert: "文章已被刪除"
	end

	private

	def note_params
		params.require(:note).permit(:title, :content)
	end

	def find_note
		@note = Note.find(params[:id])
	end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm sticky-top navbar-dark bg-dark">
  <div class="container">
    <% if user_signed_in? %>
      <%= link_to notes_path, class: "navbar-brand" do %>
        <i class="fa fa-pencil-ruler"></i>NOTENOTE
      <% end %>
    <% else %>
      <%= link_to welcomes_index_path, class: "navbar-brand" do %>
        <i class="fa fa-pencil-ruler"></i>NOTENOTE
      <% end %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New Note", new_note_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_message.html.erb
<% if flash[:notice] %>
  <div class="container">
    <div class="alert alert-info alert-dismissible fade show" role="alert">
      <strong><%= notice %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <strong><%= alert %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoteNote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/message" %>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<section id="section_note_form">
	<div class="container mt-5">
		<div class="row">
			<div class="col-8 offset-2">
				
				<%= form_for @note do |f| %>

					<% if @note.errors.any? %>
						<h2>We have some errors here !</h2>
						<ul>
							<% @note.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					<% end %>

					<div class="form-group">
						<span class="text-danger">*</span>
						<%= f.label :title, "Title：" %>
						<%= f.text_field :title, class: "form-control" %>
					</div>

					<div class="form-group">
						<span class="text-danger">*</span>
						<%= f.label :content, "Content" %>
						<%= f.text_area :content, rows: "15", class: "form-control" %>
					</div>

					<div class="form-group">
						<%= f.submit class: "btn btn-success btn-lg" %>
					</div>

				<% end %>

			</div>
		</div>
	</div>
</section>

app/views/notes/edit.html.erb
<%= render "form" %>

app/views/notes/index.html.erb
<section id="section_note_index">
	<div class="container mt-5">
		<div class="row">
				
			<% unless @notes.blank? %>
				<% @notes.each do |note| %>
					<div class="col-4">
						<%= link_to note_path(note), class: "card mb-5", style: "text-decoration: none;" do %>
					    <div class="card-body">
					      <h5 class="card-title"><%= note.title %></h5>
					    </div>
					    <div class="card-footer">
					      <small><%= time_ago_in_words(note.created_at) %></small>
					    </div>
					  <% end %>
				  </div>
				<% end %>
			<% else %>
				<div class="col-6 offset-3 mt-5">
					<div class="add_note text-center">
						<h2>Add a Note</h2>
						<p>It appears you haven't created any notes yet... Lets fix that. Why don't you go ahead and create a new note.</p>
						<% if user_signed_in? %>
							<%= link_to "New Note", new_note_path, class: "btn btn-outline-warning btn-lg" %>
						<% else %>
							<%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-success btn-lg" %>
						<% end %>
					</div>
				</div>
			<% end %>

		</div>
	</div>
</section>

app/views/notes/new.html.erb
<%= render "form" %>

app/views/notes/show.html.erb
<section id="section_note_show">
	<div class="container mt-5">
		<div class="row">
			<div class="col-8 offset-2">
				
				<div class="card">
				  <div class="card-header"><h4><%= @note.title %></h4></div>
				  <ul class="list-group list-group-flush">
				    <li class="list-group-item"><%= simple_format(@note.content) %></li>
				    <% if user_signed_in? %>
					    <li class="list-group-item">
					    	<div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
					    		<%= link_to "Edit", edit_note_path, class: "btn btn-secondary" %>
					    		<%= link_to "Delete", note_path(@note), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-secondary" %>
								</div>
					    </li>
				    <% end %>
				  </ul>
				</div>

			</div>
		</div>
	</div>
</section>

app/views/welcomes/index.html.erb
<div class="jumbotron jumbotron-fluid d-flex flex-row align-items-center">
  <div class="container text-center">
  	<h1 class="display-4">NOTENOTE</h1>
  	<p class="lead">Your online notebook. Never forget an idea again.</p>
  	<%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-success btn-lg" %>
  </div>
</div>